# Generated by Django 4.2.19 on 2025-05-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hombenai",
            name="unique_id",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
